name: Code Review Workflow

on: [pull_request]

jobs:
  hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=all_changed_files::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
        shell: bash
  
      - name: Review code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
          ollama pull mistral
  
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            content=$(cat "$file")
            review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "${{ inputs.model }}", "prompt": "Review the following file:\n\n```\n'"$content"'\n```", "stream": false}' | jq -r '.response')
            comment="Ollama Code Review for \`$file\`:\n\n$review"
            echo "$comment" >> ollama_review.txt
          done
          gh pr comment ${{ github.event.pull_request.number }} --body "$(cat ollama_review.txt)"
        shell: bash
